app:
  name: pulseReceiver
  version: 1.0.0

logger:
  log_level: info

server:
  port: 8085
  readTimeout: 10s
  writeTimeout: 10s

integration:
  otlp:
    url: localhost:4317
    protocol: grpc
    timeout: 20s
  kafka:
    url: localhost:29092
    groupId: pulse-receiver
    workTask: 30
    batchSize: 10
    batchLimit: 500
    poll: 100