app:
  name: pulseReceiver
  version: 1.0.0

logger:
  log_level: info

server:
  port: 8085
  readTimeout: 10s
  writeTimeout: 10s

integration:
  kafka:
    url: localhost:29092
    groupId: pulse-receiver
    workTask: 5
    batchSize: 10
    batchLimit: 500
    poll: 100
  
  postgres:
    host: localhost
    port: 5432
    username: docker
    password: docker
    dbname: cloudgauge
    schema: pulsereceiver
    maxIdleConns: 10
    MaxOpenConns: 100
    
  scheduled:
    aggregateCurrentHour: 2m
