// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/usageaggregation/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/usageaggregation/interfaces.go -destination=./internal/mocks/interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usageaggregation "github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregation"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageAggregationRepository is a mock of UsageAggregationRepository interface.
type MockUsageAggregationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageAggregationRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageAggregationRepositoryMockRecorder is the mock recorder for MockUsageAggregationRepository.
type MockUsageAggregationRepositoryMockRecorder struct {
	mock *MockUsageAggregationRepository
}

// NewMockUsageAggregationRepository creates a new mock instance.
func NewMockUsageAggregationRepository(ctrl *gomock.Controller) *MockUsageAggregationRepository {
	mock := &MockUsageAggregationRepository{ctrl: ctrl}
	mock.recorder = &MockUsageAggregationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageAggregationRepository) EXPECT() *MockUsageAggregationRepositoryMockRecorder {
	return m.recorder
}

// FindPending mocks base method.
func (m *MockUsageAggregationRepository) FindPending(ctx context.Context) ([]usageaggregation.UsageAggregation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPending", ctx)
	ret0, _ := ret[0].([]usageaggregation.UsageAggregation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPending indicates an expected call of FindPending.
func (mr *MockUsageAggregationRepositoryMockRecorder) FindPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPending", reflect.TypeOf((*MockUsageAggregationRepository)(nil).FindPending), ctx)
}

// FindToDispatch mocks base method.
func (m *MockUsageAggregationRepository) FindToDispatch(ctx context.Context, tenant, sku, useUnity string) ([]usageaggregation.UsageAggregation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindToDispatch", ctx, tenant, sku, useUnity)
	ret0, _ := ret[0].([]usageaggregation.UsageAggregation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindToDispatch indicates an expected call of FindToDispatch.
func (mr *MockUsageAggregationRepositoryMockRecorder) FindToDispatch(ctx, tenant, sku, useUnity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindToDispatch", reflect.TypeOf((*MockUsageAggregationRepository)(nil).FindToDispatch), ctx, tenant, sku, useUnity)
}

// Save mocks base method.
func (m *MockUsageAggregationRepository) Save(ctx context.Context, usage *usageaggregation.UsageAggregation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, usage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUsageAggregationRepositoryMockRecorder) Save(ctx, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUsageAggregationRepository)(nil).Save), ctx, usage)
}

// UpdateStatusAfterAttempt mocks base method.
func (m *MockUsageAggregationRepository) UpdateStatusAfterAttempt(ctx context.Context, usage *usageaggregation.UsageAggregation, success bool, errorMessage *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusAfterAttempt", ctx, usage, success, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusAfterAttempt indicates an expected call of UpdateStatusAfterAttempt.
func (mr *MockUsageAggregationRepositoryMockRecorder) UpdateStatusAfterAttempt(ctx, usage, success, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusAfterAttempt", reflect.TypeOf((*MockUsageAggregationRepository)(nil).UpdateStatusAfterAttempt), ctx, usage, success, errorMessage)
}

// MockUsageAggregationService is a mock of UsageAggregationService interface.
type MockUsageAggregationService struct {
	ctrl     *gomock.Controller
	recorder *MockUsageAggregationServiceMockRecorder
	isgomock struct{}
}

// MockUsageAggregationServiceMockRecorder is the mock recorder for MockUsageAggregationService.
type MockUsageAggregationServiceMockRecorder struct {
	mock *MockUsageAggregationService
}

// NewMockUsageAggregationService creates a new mock instance.
func NewMockUsageAggregationService(ctrl *gomock.Controller) *MockUsageAggregationService {
	mock := &MockUsageAggregationService{ctrl: ctrl}
	mock.recorder = &MockUsageAggregationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageAggregationService) EXPECT() *MockUsageAggregationServiceMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockUsageAggregationService) Save(ctx context.Context, payload usageaggregation.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUsageAggregationServiceMockRecorder) Save(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUsageAggregationService)(nil).Save), ctx, payload)
}
