// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/usageaggregationhistory/usegeaggregationhistory_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/usageaggregationhistory/usegeaggregationhistory_interfaces.go -destination=./internal/mocks/usegeaggregationhistory_interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usageaggregationhistory "github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregationhistory"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageAggregationHistoryRepository is a mock of UsageAggregationHistoryRepository interface.
type MockUsageAggregationHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageAggregationHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageAggregationHistoryRepositoryMockRecorder is the mock recorder for MockUsageAggregationHistoryRepository.
type MockUsageAggregationHistoryRepositoryMockRecorder struct {
	mock *MockUsageAggregationHistoryRepository
}

// NewMockUsageAggregationHistoryRepository creates a new mock instance.
func NewMockUsageAggregationHistoryRepository(ctrl *gomock.Controller) *MockUsageAggregationHistoryRepository {
	mock := &MockUsageAggregationHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockUsageAggregationHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageAggregationHistoryRepository) EXPECT() *MockUsageAggregationHistoryRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockUsageAggregationHistoryRepository) Save(ctx context.Context, usage *usageaggregationhistory.UsageAggregationHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, usage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUsageAggregationHistoryRepositoryMockRecorder) Save(ctx, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUsageAggregationHistoryRepository)(nil).Save), ctx, usage)
}
