// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/google/wire"
	"github.com/lucasd-coder/pulseReceiver/internal/controller"
	"github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregation"
	"github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregation/repository"
	"github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregation/service"
	"github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregationhistory"
	repository2 "github.com/lucasd-coder/pulseReceiver/internal/domain/usageaggregationhistory/repository"
	"github.com/lucasd-coder/pulseReceiver/internal/processor"
	"github.com/lucasd-coder/pulseReceiver/internal/provider/postgres"
	"github.com/lucasd-coder/pulseReceiver/internal/provider/validator"
	"github.com/lucasd-coder/pulseReceiver/internal/shared"
)

// Injectors from wire.go:

func InitializeProcessor() *processor.Processor {
	validation := &validator.Validation{}
	db := postgres.GetConn()
	usageAggregationRepository := repository.NewUsageAggregationRepository(db)
	usageAggregationHistoryRepository := repository2.NewUsageAggregationHistoryRepository(db)
	serviceImpl := service.NewService(validation, usageAggregationRepository, usageAggregationHistoryRepository)
	processorProcessor := processor.NewProcessor(serviceImpl)
	return processorProcessor
}

func InitializeUsageAggregationController() *controller.UsageAggregationController {
	validation := &validator.Validation{}
	db := postgres.GetConn()
	usageAggregationRepository := repository.NewUsageAggregationRepository(db)
	usageAggregationHistoryRepository := repository2.NewUsageAggregationHistoryRepository(db)
	serviceImpl := service.NewService(validation, usageAggregationRepository, usageAggregationHistoryRepository)
	usageAggregationController := controller.NewUsageAggregationController(serviceImpl)
	return usageAggregationController
}

// wire.go:

var initializeValidator = wire.NewSet(wire.Struct(new(validator.Validation)), wire.Bind(new(shared.Validator), new(*validator.Validation)))

var initializeUsageAggregationRepository = wire.NewSet(wire.Bind(new(usageaggregation.UsageAggregationRepository), new(*repository.UsageAggregationRepository)), repository.NewUsageAggregationRepository)

var initializeUsageAggregationHistoryRepository = wire.NewSet(wire.Bind(new(usageaggregationhistory.UsageAggregationHistoryRepository), new(*repository2.UsageAggregationHistoryRepository)), repository2.NewUsageAggregationHistoryRepository)
